import type { Level } from './types';

// The content for lessons (rounds and activities) is now dynamically generated by the AI.
// This structure just defines the curriculum path.

export const LEVEL_A1: Level = {
  id: 'a1',
  title: 'A1: Beginner',
  units: [
    {
      id: 'u1',
      title: 'Unit 1: The Basics',
      description: 'Start your journey with essential greetings, introductions, and common phrases.',
      lessons: [
        { id: 'u1l1', title: 'Greetings & Farewells', rounds: [] },
        { id: 'u1l2', title: 'Introductions', rounds: [] },
        { id: 'u1l3', title: 'Numbers 1-10', rounds: [] },
        { id: 'u1l4', title: 'Colors', rounds: [] },
        { id: 'u1l5', title: 'Common Nouns: Home', rounds: [] },
      ]
    },
    {
      id: 'u2',
      title: 'Unit 2: People & Places',
      description: 'Learn to describe people, talk about family, and navigate common places.',
      lessons: [
        { id: 'u2l1', title: 'Family Members', rounds: [] },
        { id: 'u2l2', title: 'Describing People', rounds: [] },
        { id: 'u2l3', title: 'In the City', rounds: [] },
        { id: 'u2l4', title: 'Jobs & Professions', rounds: [] },
      ]
    },
    {
      id: 'u3',
      title: 'Unit 3: Food & Daily Life',
      description: 'Discover names for foods, learn to order, and talk about your daily routine.',
      lessons: [
        { id: 'u3l1', title: 'Fruits & Vegetables', rounds: [] },
        { id: 'u3l2', title: 'Ordering at a Cafe', rounds: [] },
        { id: 'u3l3', title: 'Daily Routines', rounds: [] },
        { id: 'u3l4', title: 'Telling Time', rounds: [] },
      ]
    },
  ]
};
